meta_title: "Tripin"
meta_description: "Dare to discover ?"
meta_image: "image.jpg" # Une image dans votre dossier app/assets/images/
twitter_account: "@nounma" # indispensable pour les Twitter Cards
